version: "3.7"

services:
  django:
    container_name: audmix_django
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  frontend:
    container_name: audmix_frontend
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=True
    stdin_open: true
